# general configuration
url: http://www.zachburchill.ml
baseurl: ''

sass:
    sass_dir: ./assets

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/pawpaw.png"
  # author will appear under the avatar (optional)
  author: "Zachary Burchill"
  # tagline will appear under the title (optional)
  tagline: "Data dabbler, cognitive scientist, and Hadley Wickham aficionado"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Exclude non-site files:
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "anne_pro_macros.xlsx", "notes.txt"]

# Dependencies
markdown: kramdown
kramdown:
  syntax-highlighter:  rouge
highlighter: rouge

# Permalinks
permalink: pretty

# Hyde stuff
#baseurl: "/" # If you are making a gh-pages project blog, this is
                        # the name of your project repo, preceded by a /'
                        # Set it to just "/" if you are making a user page.
                        
baseurlknitr:  "/" # This will always be your baseurl plus an extra '/'
                                # at the end.  It's used only when knitr renders
                                # your R Markdown files.
                                
# Site-wide links
links:
  about_me:           /about/
  blog:            /blog/
  cv:            /cv.pdf
  publications:           /about/#research
  home: "/"

# Other stuff
facepic: /images/zburchill.jpg
                                

# set limit on number of post to appear on Home page
homepostlimit: 4
# The thing that gets excerpts
excerpt_separator: <!--more-->  # you can specify your own separator, of course.

# Disqus comments:
disqus:           true
shortname:        zachburchill # TO-DO: get a disqus account and change this

# Social Media
twitter:          false # add a twitter button to each post
facebook:         false # add a facebook share button to each post

author:
  name:           'Zachary Burchill'
  url:            https://zachburchill.ml

github:
  repo:           https://github.com/burchill
  

